---
- hosts: webservers
  sudo: yes
  vars:
   http_port: 8183
  tasks:
  - name: downloading and enable the EPEL repository definitions
    action: command rpm -Uvh --replacepkgs http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
  - name: ensure nginx is installed
    yum: name=nginx state=installed
  - name: modify the default config to use port {{ http_port }}
    template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf
    notify: 
    - restart nginx
  - name: as I am lazy kill the firewall instead of configuring it.
    service: name=iptables state=stopped enabled=no
  - name: ensure that nginx runs at boot time.
    service: name=nginx enabled=yes
  - debug: msg="Setup complete. Head over to http://${ansible_eth1.ipv4.address}:{{http_port}}"
  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
