---
- hosts: bigcouchservers
  sudo : yes
  tasks:
  #- name: enable the Cloudant repository
  #  copy: src=cloudant.repo dest=/etc/yum.repos.d/cloudant.repo

  - name: disable the firewall for now.
    service: name=iptables state=stopped

  #- name: add an entry in /etc/hosts to associate 127.0.0.1 with $hostname
  #  lineinfile: dest=/etc/hosts regexp='^127\.0\.0\.1\s${hostvars.${item}.bar}' insertafter=EOF line='127.0.0.1 ${hostvars.${item}.bar}'

  - name: print the hostname
    debug: msg="ipaddress is ${hostvars.${item}.ansible_eth1.ipv4.address}, bar is ${hostvars.${item}.bar}"
    with_items: '{{groups.bigcouchservers}}'

  - name: add entries in /etc/hosts to associate the hosts IP addresses with their hostnames.
    lineinfile: dest=/etc/hosts regexp='^${hostvars.${item}.ansible_eth1.ipv4.address}' state=present line='${hostvars.${item}.ansible_eth1.ipv4.address} ${hostvars.${item}.bar}' insertafter=EOF
    with_items: '{{groups.all}}'

  #- name: install BigCouch
  #  yum: name=bigcouch state=installed
